### PR TITLE
Add randint , setstatus and shutdown commands :)

### PR DESCRIPTION
**Pull request by pieckenst**
Signed-off-by: pieckenst <rsncra@gmail.com>

### CODE REVIEW

**Comment by pieckenst** [comment]
@spacesanjeet Please merge as a last minute thing

**Comment by spacesanjeet** [comment]
> 
> 
> @spacesanjeet Please merge as a last minute thing

Will do it.

**Comment by spacesanjeet** [comment]
@pieckenst merged.

**Comment by pieckenst** [comment]
thank you :)

**Pull request merged**
